name: InstaWP WordPress Testing

on:
  pull_request:
    types: []

jobs:
  create-wp-for-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: instawp/wordpress-testing-automation@main
        if: github.event.action == 'opened'
        id: create-wp
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          INSTAWP_TOKEN: ${{secrets.INSTAWP_TOKEN}}
          INSTAWP_DOMAIN: ${{secrets.INSTAWP_DOMAIN}}
          INSTAWP_TEMPLATE_SLUG: gitprivatedemo
          REPO_ID: 4
          INSTAWP_ACTION: create-site-template
      - run: echo URL ${{ steps.create-wp.outputs.instawp_url }}
        shell: bash
        
  destroy-wp-after-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: instawp/wordpress-testing-automation@main
        if: github.event.action == 'closed' || github.event.action == 'merged'
        id: detroy-wp
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          INSTAWP_TOKEN: ${{secrets.INSTAWP_TOKEN}}
          INSTAWP_DOMAIN: ${{secrets.INSTAWP_DOMAIN}}
          INSTAWP_TEMPLATE_SLUG: gitprivatedemo
          REPO_ID: 4
          INSTAWP_ACTION: destroy-site
